React capstone
faisalakb/React-Redux-Capstone pull request #2
Opened 2023-09-15 17:52 UTC by faisalakb

In this react capstone project apply the following features :

-  Home page :+1: 

When the page loads, the webapp shows all countries that could be filtered out by some parameter, for example by  the category name.
When the user clicks (or taps) on a region from menu, the application navigates to open countries related to select region.

- Details page :+1: 
  
 In the details page, the webapp retrieves data from the API to show detailed data.
 When the user clicks on the "Back" button (<), the user navigates to the home page.

- Use React components. :+1: 
- Use React props. :+1: 
- Use React Router. :+1: 
- Connect React and Redux. :+1: 
- Handle events in a React app. :+1: 
- Write integration tests with a React testing library. :+1: 
- Use styles in a React app. :+1: 
- Use React life cycle methods. :+1: 
- Apply React best practices and language style guides in code. :+1: 
- Use store, actions and reducers in React. :+1:

2023-09-15 20:49 UTC, OyePriscilla requested changes
Hi @faisalakb 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Use React components. ✔️ 
Use React props. ✔️
Use React Router. ✔️
Connect React and Redux. ✔️
Handle events in a React app. ✔️
Write integration tests with a React testing library. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 20:49 UTC, OyePriscilla commented on src/setupTests.js
>  import '@testing-library/jest-dom';
- [ ] Please kindly ensure that no linters are disabled, linters are there to help us write code efficiently. ℹ️

2023-09-15 20:49 UTC, OyePriscilla commented on src/component/Country/CountryDetail/CountryDetailes.test.js
- [ ] For neat and proper file organization, kindly ensure that all the test files are grouped in a folder. This will enhance the accessibility of your app. ℹ️

2023-09-15 20:49 UTC, OyePriscilla commented on src/App.js
> +        <Route path=":code" element={<CountryDetail />} />
- [ ] Please kindly ensure that your design for both homepage and detail page is very close to the given template, the only thing that does not need to be the same as stated in the guideline is the **colour** (but ensure that you're consistent with one main color chosen).

| Your Design for Homepage | Given template for Homepage |
| ------------- | ------------- |
| <img width="236" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/99b17bd3-4d39-44ba-bac2-cf665d50307d">  | <img width="146" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/89aa2857-1ba6-472c-8ceb-aa156ab7fd06">  |

| Your Design for Detail page | Given template for Detail page |
| ------------- | ------------- |
| <img width="287" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/b0aaf954-b49f-473b-8b3d-6041be80d40e"> | <img width="144" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/23147907-83ed-497f-8398-c44a07f56f0a"> |

## Project Guideline

<img width="361" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/0e7566b5-be90-4885-befd-e429503c5314">

2023-09-15 20:49 UTC, OyePriscilla commented on src/feature/countries/countriesAction.js
The directory name for this implementation is not descriptive enough (**redux** is much more descriptive I think), the word **feature** seems to be general and not specific. 🙏 

<img width="226" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/b8cfd664-cb17-44e3-9de1-aed1e8b0c88d">

2023-09-15 20:49 UTC, OyePriscilla commented on src/component/Country/aCountry/singleCountryInfo.jsx
> +        </div>
- [optional] Please kindly ensure that the map you intend to display is accessible, at the moment; I got the error screenshot below 👇  

<img width="533" alt="Untitled" src="https://github.com/faisalakb/React-Redux-Capstone/assets/103386183/cfc26cae-63c0-48fa-ad81-c89d6e32993c">

2023-09-16 13:07 UTC, skyv26 requested changes
## Hi @faisalakb, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDMzYmY2ZWU0MmEwMTJjZTczMGVhNDhlM2E2NWViYmQ0YzY5ZTBiNiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/17FxSFyYNOgThnonDK/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 
- Used correct `GitFlow` ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 13:07 UTC, skyv26 commented on src/App.js
> +        <Route path=":code" element={<CountryDetail />} />
- [ ] Kindly adhere to the project requirement, your previous code reviewer also mentioned it, even though you did a great job by making the changes still you need to make your design look as close as possible to the `Behance` design. You can even compare your design in the below given table, can easily figure out that you are missing a few things that need to be added to pass this capstone project. Implementing the things as per the given design will make you more better and detail-oriented developer.

### Requirement
![image](https://user-images.githubusercontent.com/103386183/268376852-0e7566b5-be90-4885-befd-e429503c5314.png)

### Home Design Comparison
<table>
<tr>
<th>Behance Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![Screenshot from 2023-05-04 14-58-52](https://user-images.githubusercontent.com/103386183/268375466-89aa2857-1ba6-472c-8ceb-aa156ab7fd06.png)

</td>
<td>

![Screenshot from 2023-09-16 18-23-01](https://github.com/faisalakb/React-Redux-Capstone/assets/66476329/cc1f5d31-b11d-4584-9a01-6d5f6858536e)


</td>
</tr>
</table>

### Detail Design Comparison

<table>
<tr>
<th>Behance Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![Screenshot from 2023-05-04 14-58-52](https://user-images.githubusercontent.com/103386183/268376542-23147907-83ed-497f-8398-c44a07f56f0a.png)

</td>
<td>

![Screenshot from 2023-09-16 18-30-01](https://github.com/faisalakb/React-Redux-Capstone/assets/66476329/e469bdd8-ced2-4680-b003-21a6a8509165)


</td>
</tr>
</table>

2023-09-16 13:07 UTC, skyv26 commented on src/setupTests.js
- [ ] Your previous code reviewer asked for changes to remove the `eslinter` disabled comment, but it seems like you didn't implement the changes. In my opinion, if you don't need this file, please delete it to overcome the problem, otherwise try to resolve the issues and re-submit your project for review.

2023-09-16 16:51 UTC, faisalakb commented
Please check. i address all the above issues.

2023-09-16 17:08 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @faisalakb   👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: - The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:


### Optional Suggestions



**_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 17:16 UTC, faisalakb commented
Thanks for the time and review

2023-09-16 17:16 UTC, merged